name: MMODungeonPlugin
main: com.nordryd.Main
version: 1.0
api-version: 1.14
load: startup
commands:
   mmod.region_edit_tool:
      description: Gives the player a region editing tool.
      usage: Usage = /mmod.region_edit_tool
      permission: mmod.admin
      permission-message: You don't have permission to use mmod.region_edit_tool
permissions:
  mmod.admin:
    description: Gives access to all commands.
    default: op
    children:
      mmod.user: true
  mmod.user:
    description: Gives access to commands that do not enable grieving.